/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const CommonStatusEnum: typeof import('../src/utils/constants').CommonStatusEnum
  const DICT_TYPE: typeof import('../src/utils/dict').DICT_TYPE
  const EffectScope: typeof import('vue').EffectScope
  const ElLoading: typeof import('element-plus').ElLoading
  const ElMessage: typeof import('element-plus').ElMessage
  const ElMessageBox: typeof import('element-plus').ElMessageBox
  const ElNotification: typeof import('element-plus').ElNotification
  const FormContextKey: typeof import('../src/composables/useVeeForm').FormContextKey
  const SEASON_META: typeof import('../src/composables/useSeasonEffect').SEASON_META
  const STATUS_ID_TO_LABEL: typeof import('../src/composables/useCalendarData').STATUS_ID_TO_LABEL
  const SystemDataScopeEnum: typeof import('../src/utils/constants').SystemDataScopeEnum
  const SystemMenuTypeEnum: typeof import('../src/utils/constants').SystemMenuTypeEnum
  const UserStatusEnum: typeof import('../src/utils/constants').UserStatusEnum
  const alovaInstance: typeof import('../src/utils/http').alovaInstance
  const apiMenuToMenuItem: typeof import('../src/utils/menuUtils').apiMenuToMenuItem
  const buildMenuTree: typeof import('../src/utils/menuUtils').buildMenuTree
  const checkSelectedNode: typeof import('../src/utils/tree').checkSelectedNode
  const computed: typeof import('vue').computed
  const convertBlockingSlotToEvent: typeof import('../src/composables/useCalendarData').convertBlockingSlotToEvent
  const convertLessonToEvent: typeof import('../src/composables/useCalendarData').convertLessonToEvent
  const convertSlotToEvent: typeof import('../src/composables/useCalendarData').convertSlotToEvent
  const correctNow: typeof import('../src/utils/serverTime').correctNow
  const createApp: typeof import('vue').createApp
  const createEmailRule: typeof import('../src/utils/formRules').createEmailRule
  const createIntegerRule: typeof import('../src/utils/formRules').createIntegerRule
  const createLengthBetweenRule: typeof import('../src/utils/formRules').createLengthBetweenRule
  const createLengthMaxRule: typeof import('../src/utils/formRules').createLengthMaxRule
  const createLengthMinRule: typeof import('../src/utils/formRules').createLengthMinRule
  const createNameLikeRules: typeof import('../src/utils/formRules').createNameLikeRules
  const createNumberMaxRule: typeof import('../src/utils/formRules').createNumberMaxRule
  const createNumberMinRule: typeof import('../src/utils/formRules').createNumberMinRule
  const createNumberRule: typeof import('../src/utils/formRules').createNumberRule
  const createPhoneRule: typeof import('../src/utils/formRules').createPhoneRule
  const createRequiredRule: typeof import('../src/utils/formRules').createRequiredRule
  const createRequiredSelectRule: typeof import('../src/utils/formRules').createRequiredSelectRule
  const createUrlRule: typeof import('../src/utils/formRules').createUrlRule
  const customRef: typeof import('vue').customRef
  const dateFormatter: typeof import('../src/utils/formatTime').dateFormatter
  const dayjs: typeof import('../src/utils/dayjs').default
  const defaultProps: typeof import('../src/utils/tree').defaultProps
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const dompurifyDirectiveConfig: typeof import('../src/utils/dompurify').dompurifyDirectiveConfig
  const download: typeof import('../src/utils/download').default
  const eachTree: typeof import('../src/utils/tree').eachTree
  const effectScope: typeof import('vue').effectScope
  const filter: typeof import('../src/utils/tree').filter
  const findNode: typeof import('../src/utils/tree').findNode
  const findNodeAll: typeof import('../src/utils/tree').findNodeAll
  const findPath: typeof import('../src/utils/tree').findPath
  const findPathAll: typeof import('../src/utils/tree').findPathAll
  const forEach: typeof import('../src/utils/tree').forEach
  const formatDate: typeof import('../src/utils/dayjs').formatDate
  const formatDateTime: typeof import('../src/utils/dayjs').formatDateTime
  const formatRelative: typeof import('../src/utils/dayjs').formatRelative
  const getAppConfig: typeof import('../src/utils/appConfig').getAppConfig
  const getAutoSeason: typeof import('../src/composables/useSeasonEffect').getAutoSeason
  const getBoolDictOptions: typeof import('../src/utils/dict').getBoolDictOptions
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getDictLabel: typeof import('../src/utils/dict').getDictLabel
  const getDictObj: typeof import('../src/utils/dict').getDictObj
  const getDictOptions: typeof import('../src/utils/dict').getDictOptions
  const getDictOverrides: typeof import('../src/utils/dictOverrides').getDictOverrides
  const getGrowthBook: typeof import('../src/utils/analytics').getGrowthBook
  const getIntDictOptions: typeof import('../src/utils/dict').getIntDictOptions
  const getNow: typeof import('../src/utils/serverTime').getNow
  const getStrDictOptions: typeof import('../src/utils/dict').getStrDictOptions
  const getTimeMs: typeof import('../src/utils/serverTime').getTimeMs
  const h: typeof import('vue').h
  const handleTree: typeof import('../src/utils/tree').handleTree
  const handleTree2: typeof import('../src/utils/tree').handleTree2
  const http: typeof import('../src/utils/http').default
  const init: typeof import('../src/utils/serverTime').init
  const initAnalytics: typeof import('../src/utils/analytics').initAnalytics
  const initErrorReport: typeof import('../src/utils/errorReport').initErrorReport
  const initGrowthBook: typeof import('../src/utils/analytics').initGrowthBook
  const initMatomo: typeof import('../src/utils/analytics').initMatomo
  const initWebUpdateNotice: typeof import('../src/utils/webUpdateNotice').initWebUpdateNotice
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isReady: typeof import('../src/utils/serverTime').isReady
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const isUrl: typeof import('../src/utils/menuUtils').isUrl
  const listToTree: typeof import('../src/utils/tree').listToTree
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const parseBusinessHoursString: typeof import('../src/composables/useCalendarData').parseBusinessHoursString
  const pathResolve: typeof import('../src/utils/menuUtils').pathResolve
  const propTypes: typeof import('../src/utils/propTypes').propTypes
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const reportClientError: typeof import('../src/utils/errorReport').reportClientError
  const resolveComponent: typeof import('vue').resolveComponent
  const serverTime: typeof import('../src/utils/serverTime').default
  const setDayjsLocale: typeof import('../src/utils/dayjs').setDayjsLocale
  const setDictOverrides: typeof import('../src/utils/dictOverrides').setDictOverrides
  const setupI18n: typeof import('../src/utils/i18n').setupI18n
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const splitScheduleByBlockers: typeof import('../src/composables/useCalendarData').splitScheduleByBlockers
  const splitSchedulesAndBlockers: typeof import('../src/composables/useCalendarData').splitSchedulesAndBlockers
  const statusIdToClassName: typeof import('../src/composables/useCalendarData').statusIdToClassName
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toTypedSchema: typeof import('../src/composables/useVeeForm').toTypedSchema
  const toValue: typeof import('vue').toValue
  const trackMatomoEvent: typeof import('../src/utils/analytics').trackMatomoEvent
  const trackMatomoPageView: typeof import('../src/utils/analytics').trackMatomoPageView
  const trackRouteTiming: typeof import('../src/utils/performance').trackRouteTiming
  const treeMap: typeof import('../src/utils/tree').treeMap
  const treeMapEach: typeof import('../src/utils/tree').treeMapEach
  const treeToList: typeof import('../src/utils/tree').treeToList
  const treeToString: typeof import('../src/utils/tree').treeToString
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useCalendarData: typeof import('../src/composables/useCalendarData').useCalendarData
  const useCountdown: typeof import('../src/composables/useCountdown').useCountdown
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useField: typeof import('../src/composables/useVeeForm').useField
  const useForm: typeof import('../src/composables/useVeeForm').useForm
  const useId: typeof import('vue').useId
  const useModel: typeof import('vue').useModel
  const useRouteLoading: typeof import('../src/composables/useRouteLoading').useRouteLoading
  const useSeasonEffect: typeof import('../src/composables/useSeasonEffect').useSeasonEffect
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
  const z: typeof import('../src/composables/useVeeForm').z
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { ScheduleSlot, Lesson, BlockingSlot, TimeRangeLike, TimeRangeMs, ScheduleSegment, CalendarEvent, BusinessHoursSegment } from '../src/composables/useCalendarData'
  import('../src/composables/useCalendarData')
  // @ts-ignore
  export type { Season, SeasonTheme, SeasonMeta } from '../src/composables/useSeasonEffect'
  import('../src/composables/useSeasonEffect')
  // @ts-ignore
  export type { DateInput } from '../src/utils/dayjs'
  import('../src/utils/dayjs')
  // @ts-ignore
  export type { DictDataType, NumberDictDataType, StringDictDataType } from '../src/utils/dict'
  import('../src/utils/dict')
  // @ts-ignore
  export type { ReportContext } from '../src/utils/errorReport'
  import('../src/utils/errorReport')
  // @ts-ignore
  export type { MenuItem, ApiMenuVO } from '../src/utils/menuUtils'
  import('../src/utils/menuUtils')
  // @ts-ignore
  export type { FetchServerTime, ServerTimeInitOptions } from '../src/utils/serverTime'
  import('../src/utils/serverTime')
}
